dataset<-read.table("household_power_consumption.txt",header=TRUE,sep=";",dec=".")
dataset$Date2<-as.Date(as.character(dataset$Date),"%d/%m/%Y")
newdata<-subset(dataset,Date2 >= as.Date("2007-02-01"))
newdata2<-subset(newdata,Date2 <= as.Date("2007-02-02"))
newdata2$datetime<-strptime(paste(newdata2$Date,newdata2$Time), format = "%d/%m/%Y %H:%M:%OS")
print(head(newdata2))
png(file="plot4.png")
par(mfcol=c(2,2))
with(newdata2,plot(datetime,as.numeric(Global_active_power),type="l",ylab="Global Active Power (kilowatts)",xlab=""))
with(newdata2,plot(datetime,as.numeric(Sub_metering_1),type="l",ylab="Energy sub metering",xlab="",col="black"))
with(newdata2, lines(datetime, as.numeric(Sub_metering_2),col="red",type="l"))
with(newdata2, lines(datetime, as.numeric(Sub_metering_3),col="blue",type="l"))
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,bty="n")
with(newdata2,plot(datetime,as.numeric(Voltage),type="l",ylab="Voltage"))
with(newdata2,plot(datetime,as.numeric(Global_reactive_power),type="l",ylab="Global_reactive_power"))
dev.off()