dataset<-read.table("household_power_consumption.txt",header=TRUE,sep=";",dec=".")
dataset$Date2<-as.Date(as.character(dataset$Date),"%d/%m/%Y")
newdata<-subset(dataset,Date2 >= as.Date("2007-02-01"))
newdata2<-subset(newdata,Date2 <= as.Date("2007-02-02"))
newdata2$datetime<-strptime(paste(newdata2$Date,newdata2$Time), format = "%d/%m/%Y %H:%M:%OS")
print(head(newdata2))
png(file="plot2.png")
with(newdata2,plot(datetime,as.numeric(Global_active_power),type="l",ylab="Global Active Power (kilowatts)",xlab=""))
dev.off()